export const imageSrcs = [
  "/images/carousel/Image1.webp",
  "/images/carousel/Image2.webp",
  "/images/carousel/Image3.webp",
  "/images/carousel/Image4.webp",
  "/images/carousel/Image5.webp",
  "/images/carousel/Image6.webp",
  "/images/carousel/Image7.webp",
  "/images/carousel/Image8.webp",
  "/images/carousel/Image9.webp",
  "/images/carousel/Image10.webp",
  "/images/carousel/Image11.webp",
  "/images/carousel/Image12.webp",
  "/images/carousel/Image13.webp",
  "/images/carousel/Image14.webp",
  "/images/carousel/Image15.webp",
  "/images/carousel/Image16.webp",
];
