export const imageSrcs = [
  "/images/carousel/01.jpg",
  "/images/carousel/02.jpg",
  "/images/carousel/03.jpg",
  "/images/carousel/04.jpg",
  "/images/carousel/05.jpg",
  "/images/carousel/06.jpg",
  "/images/carousel/07.jpg",
  "/images/carousel/08.jpg",
  "/images/carousel/09.jpg",
  "/images/carousel/10.jpg",
  "/images/carousel/11.jpg",
  "/images/carousel/12.jpg",
  "/images/carousel/13.jpg",
  "/images/carousel/14.jpg",
  "/images/carousel/15.jpg",
];
