export const partners = [
  {
    partnership: "Gift Partner",
    image: "/images/companies/alaris-lanka.png",
    link: "",
    description: "Providing gifts for the event",
  },
  {
    partnership: "Gift Partner",
    image: "/images/companies/ceylon-biscuits.png",
    link: "",
    description: "Providing gifts for the event",
  },
  {
    partnership: "Gift Partner",
    image: "/images/companies/facescrubs.png",
    link: "",
    description: "Providing gifts for the event",
  },
  {
    partnership: "Gift Partner",
    image: "/images/companies/slaughter.png",
    link: "",
    description: "Providing gifts for the event",
  },
  {
    partnership: "Photography Partner",
    image: "/images/companies/envalon-studio.png",
    link: "",
    description: "Providing photography services",
  },
  {
    partnership: "Photography Partner",
    image: "/images/companies/craft.png",
    link: "",
    description: "Providing photography services",
  },
  {
    partnership: "Photography Partner",
    image: "/images/companies/freeze.png",
    link: "",
    description: "Providing photography services",
  },
  {
    partnership: "Photography Partner",
    image: "/images/companies/studio-click.png",
    link: "",
    description: "Providing photography services",
  },
  {
    partnership: "Event Partner",
    image: "/images/companies/imagine-entertainment.png",
    link: "",
    description: "Handling event management",
  },
  {
    partnership: "Printing Partner",
    image: "/images/companies/wristband-lanka.png",
    link: "https://wristbandlanka.lk/",
    description: "Providing printing services",
  },
  {
    partnership: "Printing Partner",
    image: "/images/companies/flexport-innovations.png",
    link: "",
    description: "Providing printing services",
  },
  {
    partnership: "Beautycare Partner",
    image: "/images/companies/queens-beauticians.png",
    link: "",
    description: "Providing beauty care services",
  },
  {
    partnership: "Entertainment Partner",
    image: "/images/companies/flair-club.png",
    link: "",
    description: "Providing entertainment for the event",
  },
  {
    partnership: "Official Printed Media Partner",
    image: "/images/companies/ceylon-newspapers.png",
    link: "",
    description: "Providing printed media coverage",
  },
];
